development:
  host: ftp.bookcraft.co.uk
  directory: public_html/upload_testing

production:
  host: ftp.production.co.uk
  directory: test

ignored_prefixes:
  - 'ignored_dir'
  - '.git'

ignored_suffixes:
  - '.swp'

local_directory: 'test_files'
